version: "3.9"
services:
#  app:
#    container_name: hw12-app
#    build: ../build
#    ports:
#      - "8080:8080"
#    restart: on-failure
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=hw
#    volumes:
#      - ../:/usr/src/app/
#    depends_on:
#      - db
#    networks:
#      - hw12-network

  db:
    image: postgres:latest
    container_name: hw12-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hw
    ports:
      - '5432:5432'
    volumes:
      - hw12-pg-volume:/var/lib/postgresql/data
    networks:
      - hw12-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: hw12-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuzmindv@gamil.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    depends_on:
      - db
    ports:
      - "16543:80"
    networks:
      - hw12-network
    restart: unless-stopped

volumes:
#  api:
  db:
  hw12-pg-volume:
    external: true

# Networks to be created to facilitate communication between containers
networks:
  hw12-network:
    driver: bridge
